"""
CAM (Credit Appraisal Memo) Report Generator
Generates professional credit appraisal reports
"""
from datetime import datetime
from typing import Dict, Optional

def generate_cam_report(
    company_name: str,
    financial_data: Dict,
    ml_prediction: Dict,
    loan_recommendation: Dict,
    research_data: Optional[Dict] = None
) -> str:
    """
    Generate Credit Appraisal Memo (CAM) report
    Returns: Formatted CAM report as string
    """
    
    report = []
    
    # Header
    report.append("="*80)
    report.append("CREDIT APPRAISAL MEMO (CAM)")
    report.append("="*80)
    report.append(f"\nCompany Name: {company_name}")
    report.append(f"Report Date: {datetime.now().strftime('%d %B %Y')}")
    report.append(f"Generated By: Intelli-Credit AI System")
    report.append("\n" + "="*80)
    
    # Section 1: Executive Summary
    report.append("\n1. EXECUTIVE SUMMARY")
    report.append("-"*80)
    report.append(f"Credit Decision: {loan_recommendation['decision']}")
    report.append(f"ML Risk Level: {ml_prediction['risk_level']}")
    report.append(f"Credit Score: {ml_prediction['credit_score']}/100")
    report.append(f"Probability of Default: {ml_prediction['probability_of_default']:.2%}")
    
    if loan_recommendation['loan_amount'] > 0:
        report.append(f"\nRecommended Loan Amount: Rs.{loan_recommendation['loan_amount']:,.0f}")
        report.append(f"Suggested Interest Rate: {loan_recommendation['interest_rate']}% p.a.")
        report.append(f"Proposed Tenure: {loan_recommendation['tenure_months']} months")
    
    # Section 2: Financial Analysis
    report.append("\n\n2. FINANCIAL ANALYSIS")
    report.append("-"*80)
    report.append("\n2.1 Key Financial Metrics:")
    
    from modules.financial_extractor import format_crores
    report.append(f"  Revenue:             {format_crores(financial_data.get('revenue'))}")
    report.append(f"  Net Profit:          {format_crores(financial_data.get('net_profit'))}")
    report.append(f"  Total Assets:        {format_crores(financial_data.get('assets'))}")
    report.append(f"  Total Liabilities:   {format_crores(financial_data.get('liabilities'))}")
    report.append(f"  Total Debt:          {format_crores(financial_data.get('debt'))}")
    report.append(f"  Operating Cash Flow: {format_crores(financial_data.get('cash_flow'))}")
    
    # Section 3: ML Risk Assessment
    report.append("\n\n3. ML-BASED RISK ASSESSMENT")
    report.append("-"*80)
    report.append(f"Risk Classification: {ml_prediction['risk_level']}")
    report.append(f"Model Confidence: {ml_prediction['model_confidence']:.1%}")
    report.append(f"\nKey Risk Factors:")
    for explanation in ml_prediction['explanations']:
        report.append(f"  • {explanation}")
    
    # Section 4: Feature Importance
    report.append("\n\n4. KEY DECISION FACTORS")
    report.append("-"*80)
    report.append("Feature Importance (ML Model):")
    for feature, importance in sorted(
        ml_prediction['feature_importance'].items(),
        key=lambda x: x[1],
        reverse=True
    )[:5]:
        report.append(f"  {feature:30s}: {importance:.1%}")
    
    # Section 5: External Research
    if research_data:
        report.append("\n\n5. EXTERNAL INTELLIGENCE")
        report.append("-"*80)
        report.append(f"News Sentiment: {research_data.get('sentiment', 'N/A')}")
        report.append(f"Risk Signals Detected: {len(research_data.get('risk_signals', []))}")
        report.append(f"Articles Analyzed: {research_data.get('articles_analyzed', 0)}")
        
        if research_data.get('risk_signals'):
            report.append("\nRisk Signals:")
            for signal in research_data['risk_signals'][:3]:
                report.append(f"  • {signal}")
    
    # Section 6: Loan Recommendation
    report.append("\n\n6. LOAN RECOMMENDATION")
    report.append("-"*80)
    report.append(f"Decision: {loan_recommendation['decision']}")
    report.append(f"\nRationale:")
    report.append(f"  {loan_recommendation['explanation']}")
    
    if loan_recommendation.get('conditions'):
        report.append(f"\nConditions:")
        for condition in loan_recommendation['conditions']:
            report.append(f"  • {condition}")
    
    # Section 7: Risk Mitigation
    report.append("\n\n7. RISK MITIGATION MEASURES")
    report.append("-"*80)
    if ml_prediction['risk_level'] == "LOW":
        report.append("  • Standard monitoring procedures")
        report.append("  • Quarterly financial reviews")
    elif ml_prediction['risk_level'] == "MEDIUM":
        report.append("  • Enhanced monitoring required")
        report.append("  • Monthly financial reporting")
        report.append("  • Collateral coverage: 125%")
    else:
        report.append("  • Intensive monitoring required")
        report.append("  • Weekly cash flow tracking")
        report.append("  • Collateral coverage: 150%")
        report.append("  • Personal guarantees from promoters")
    
    # Section 8: Recommendation
    report.append("\n\n8. FINAL RECOMMENDATION")
    report.append("-"*80)
    if loan_recommendation['decision'] == "APPROVED":
        report.append("✅ RECOMMEND APPROVAL")
        report.append(f"\nThe credit committee is recommended to approve the loan facility")
        report.append(f"based on strong financial metrics and low risk profile.")
    elif loan_recommendation['decision'] == "CONDITIONAL":
        report.append("⚠️ CONDITIONAL APPROVAL")
        report.append(f"\nThe credit committee may consider approval subject to")
        report.append(f"fulfillment of specified conditions and enhanced monitoring.")
    else:
        report.append("❌ RECOMMEND REJECTION")
        report.append(f"\nThe credit committee is recommended to decline the loan facility")
        report.append(f"due to high risk profile and inadequate financial strength.")
    
    # Footer
    report.append("\n\n" + "="*80)
    report.append("END OF CREDIT APPRAISAL MEMO")
    report.append("="*80)
    report.append(f"\nDisclaimer: This report is generated by an AI system and should be")
    report.append(f"reviewed by qualified credit professionals before final decision.")
    
    return "\n".join(report)

def generate_cam_summary(ml_prediction: Dict, loan_recommendation: Dict) -> str:
    """Generate short CAM summary for display"""
    summary = f"""
**Credit Decision:** {loan_recommendation['decision']}
**ML Risk Level:** {ml_prediction['risk_level']}
**Credit Score:** {ml_prediction['credit_score']}/100
**Default Probability:** {ml_prediction['probability_of_default']:.2%}

**Loan Amount:** Rs.{loan_recommendation['loan_amount']:,.0f}
**Interest Rate:** {loan_recommendation['interest_rate']}% p.a.
**Tenure:** {loan_recommendation['tenure_months']} months
"""
    return summary
